name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t mvcproject:latest .

      - name: Save Docker image
        run: docker save mvcproject:latest | gzip > mvcproject.tar.gz

      - name: Copy image to VPS
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_SSH_KEY }}
          source: "mvcproject.tar.gz"
          target: "/opt/mvcproject"

      - name: Deploy on VPS
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd /opt/mvcproject

            docker load < mvcproject.tar.gz

            docker stop mvcproject || true
            docker rm mvcproject || true

            mkdir -p data

            docker run -d \
            --name mvcproject \
            --restart always \
            -p 8080:8080 \
            -v /opt/mvcproject/data:/app/data \
            -e ASPNETCORE_URLS=http://+:8080 \
            -e ASPNETCORE_ENVIRONMENT=Development \
            -e "ConnectionStrings__DefaultConnection=Data Source=/app/data/app.db" \
            mvcproject:latest

            docker image prune -f
